$schema: https://json-schema.org/draft/2020-12/schema
$ref: "#/$defs/RulesConfig"
$defs:
  StringComparisonBaseRule:
    oneOf:
      - type: object
        properties:
          startswith:
            type: string
          endswith:
            type: string
          contains:
            type: string
      - type: object
        properties:
          equals:
            type: string
        required:
          - equals
  BaseRule:
    type: object
    properties:
      dirpath:
        $ref: "#/$defs/StringComparisonBaseRule"
      filename:
        $ref: "#/$defs/StringComparisonBaseRule"
      content:
        $ref: "#/$defs/StringComparisonBaseRule"
  BaseRuleCombinator:
    type: object
    properties:
      or:
        type: array
        items:
          $ref: "#/$defs/BaseRule"
      xor:
        type: array
        items:
          $ref: "#/$defs/BaseRule"
      and:
        type: array
        items:
          $ref: "#/$defs/BaseRule"
    oneOf:
      - required:
          - or
      - required:
          - xor
      - required:
          - and
  Rule:
    oneOf:
      - allOf:
          - $ref: "#/$defs/BaseRule"
          - type: object
            properties:
              not:
                $ref: "#/$defs/BaseRule"
      - $ref: "#/$defs/BaseRuleCombinator"
  RuleCombinator:
    type: object
    properties:
      or:
        type: array
        items:
          $ref: "#/$defs/Rule"
      xor:
        type: array
        items:
          $ref: "#/$defs/Rule"
      and:
        type: array
        items:
          $ref: "#/$defs/Rule"
    oneOf:
      - required:
          - or
      - required:
          - xor
      - required:
          - and
  RulesConfig:
    type: object
    properties:
      rules:
        $ref: "#/$defs/RuleCombinator"
      exclude_dirs:
        type: array
        items:
          type: string
    required:
      - rules
    additionalProperties: false
