$schema: https://json-schema.org/draft/2020-12/schema
$ref: "#/$defs/RulesConfig"
$defs:
  StringComparisonBaseRule:
    oneOf:
      - type: object
        properties:
          startswith:
            type: string
            minLength: 1
          endswith:
            type: string
            minLength: 1
          contains:
            type: string
            minLength: 1
      - type: object
        properties:
          equals:
            type: string
        required:
          - equals
  NumberComparisonBaseRule:
    oneOf:
      - type: object
        properties:
          greater_than:
            type: integer
        required:
          - greater_than
      - type: object
        properties:
          less_than:
            type: integer
        required:
          - less_than
      - type: object
        properties:
          equal_to:
            type: integer
        required:
          - equal_to
  BaseRule:
    type: object
    properties:
      dirpath:
        $ref: "#/$defs/StringComparisonBaseRule"
      filename:
        $ref: "#/$defs/StringComparisonBaseRule"
      content:
        $ref: "#/$defs/StringComparisonBaseRule"
      number_of_lines:
        $ref: "#/$defs/NumberComparisonBaseRule"
  BaseRuleCombinator:
    oneOf:
      - type: object
        properties:
          or:
            type: array
            items:
              $ref: "#/$defs/BaseRule"
        required:
          - or
      - type: object
        properties:
          xor:
            type: array
            items:
              $ref: "#/$defs/BaseRule"
        required:
          - xor
      - type: object
        properties:
          and:
            type: array
            items:
              $ref: "#/$defs/BaseRule"
        required:
          - and
  Rule:
    oneOf:
      - $ref: "#/$defs/BaseRuleCombinator"
      - allOf:
          - $ref: "#/$defs/BaseRule"
          - type: object
            properties:
              not:
                $ref: "#/$defs/BaseRule"
  RuleCombinator:
    oneOf:
      - type: object
        properties:
          or:
            type: array
            items:
              $ref: "#/$defs/Rule"
        required:
          - or
      - type: object
        properties:
          xor:
            type: array
            items:
              $ref: "#/$defs/Rule"
        required:
          - xor
      - type: object
        properties:
          and:
            type: array
            items:
              $ref: "#/$defs/Rule"
        required:
          - and
  RulesConfig:
    type: object
    properties:
      rules:
        oneOf:
          - $ref: "#/$defs/RuleCombinator"
          - $ref: "#/$defs/Rule"
      ignore:
        type: array
        items:
          type: string
          minLength: 1
    required:
      - rules
    additionalProperties: false
